- name: My first play
  hosts: localhost
  tasks:
    - name: Creating user brickdev with password pass
      user:
        name: brickdev
        password: "{{ 'pass' | password_hash('sha512') }}"

    - name: Enable pub key authentication in ssh
      lineinfile:
        path: /etc/ssh/ssh_config
        regexp: "^(.*)PubkeyAuthentication(.*)$"
        line: "PubkeyAuthentication yes"

    - name: Disable root authentication in ssh
      lineinfile:
        path: /etc/ssh/ssh_config
        regexp: "^(.*)PermitRootLogin(.*)$"
        line: "PermitRootLogin no"

    - name: Ensure ssh dir exists
      file:
        path: "/home/brickdev/.ssh"
        state: directory
        mode: "0700"

    - name: Copy pubkey for brickdev
      copy:
        content: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDDW1sg+ys6EEZd6ZzbDlrMMybOBUALEtERY2/ZKsvgbcAzTERxbtsqu+iNNDBo+sf3L3YuWkd8fLH4SJ3MQV42ySc6ml2tMT0G2r+QIWwFz+nPaD2DY8blgFpsa41TZxwKgLmqEtUVlps9Q6Un5KtJMjTl2MWYKswdxSqHw8em0DNigJolWfzsmoTvd1HXTYdj/PiJECW3nS38PFlL19Av6ipwrbxme2/VyvjolX5F3p/dgLkuUU7UMQ+tlx9gAlN0F/Tf6zMHSubIBC7lOf58zP+IlykdD4leVaNpFckk9hxnKCZpyM7jlwi2YSnYLAOh4v56NTq7c/yG2jX9+lSb"
        dest: /home/brickdev/.ssh/authorized_keys
        mode: "0600"
