version: '3.8'
services:  
  app:
    build: ./
    command: node index.js
    networks:
      - app-network
    environment:
      - AUTHOR=pish
    deploy:
      replicas: 3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:8000"
    depends_on:
      - app
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
