version: '3.8'
services:  
  app-1:
    build: ./
    command: node index.js
    networks:
      - app-network
    expose:
      - 8001
    environment:
      - PORT=8001
      - INDEX=1
      - AUTHOR=pish
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:8001 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  app-2:
    build: ./
    command: node index.js
    networks:
      - app-network
    expose:
      - 8002
    environment:
      - PORT=8002
      - INDEX=2
      - AUTHOR=pish
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:8002 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  app-3:
    build: ./
    command: node index.js
    networks:
      - app-network
    expose:
      - 8003
    environment:
      - PORT=8003
      - INDEX=3
      - AUTHOR=pish
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:8003 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:8000"
    depends_on:
      - app-1
      - app-2
      - app-3
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
